[program:mlflow]
command=/home/carbon/.local/bin/mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////home/carbon/.mlflow/mlflow.db --default-artifact-root /home/carbon/mlflow-artifacts
directory=/home/carbon
user=carbon
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/mlflow/mlflow.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
