[program:superset]
command=/home/carbon/.local/bin/superset run -h 0.0.0.0 -p 8088 --with-threads
directory=/home/carbon
user=carbon
environment=SUPERSET_CONFIG_PATH="/home/carbon/superset_config.py",HOME="/home/carbon",PATH="/home/carbon/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superset/superset.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
