[program:superset]
command=/usr/local/bin/superset run -h 0.0.0.0 -p 8088 --with-threads
directory=/home/carbon
user=root
environment=SUPERSET_CONFIG_PATH="/home/carbon/superset_config.py"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superset/superset.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
